"""Seed data for NurulQuran courses. Mirrors the frontend mock content."""

COURSES_SEED = [
    {
        "id": "sabeel-ul-jannah",
        "title": "Sabeel Ul Jannah",
        "tag": "Flagship",
        "level": "All Levels",
        "language": "English",
        "duration": "2.5 Years",
        "start": "Jun 2, 2025",
        "image": "valley2",
        "desc": "A comprehensive journey through Tafseer, Seerah and character building \u2014 the path that leads to Jannah.",
        "longDesc": "Sabeel Ul Jannah is our flagship journey \u2014 a structured 2.5 year program that walks you through detailed Tafseer, the blessed Seerah and deep character building. It is designed to transform not just your knowledge, but your heart and daily life.",
        "instructor": "Senior Faculty Team",
        "days": "Tue \u2022 Thu",
        "time": "Morning & Evening slots",
        "fee": "From $50 / semester",
        "modules": [
            "Detailed word-by-word Tafseer of selected Surahs",
            "Seerah of the Prophet \u00b7 with practical lessons",
            "Foundations of Arabic for Quranic understanding",
            "Character building & spiritual purification",
        ],
        "outcomes": [
            "Understand the Quran with depth and context",
            "Build a consistent connection with Allah",
            "Apply prophetic guidance to modern life",
        ],
        "order": 1,
    },
    {
        "id": "nurun-ala-nur",
        "title": "NurunAlaNur",
        "tag": "Tafseer",
        "level": "Intermediate",
        "language": "English",
        "duration": "Semester based",
        "start": "Apr 2026",
        "image": "waterfall1",
        "desc": "Light upon light \u2014 an in-depth Tafseer of the Makki and Madani Surahs of the Holy Quran.",
        "longDesc": "NurunAlaNur \u2014 light upon light \u2014 is an in-depth Tafseer program covering the Makki and Madani Surahs of the Holy Quran, revealing the timeless wisdom within every verse.",
        "instructor": "Tafseer Faculty",
        "days": "Mon \u2022 Wed",
        "time": "Evening slot",
        "fee": "From $40 / semester",
        "modules": [
            "Asbab al-Nuzul \u2014 reasons of revelation",
            "Makki vs Madani themes and structure",
            "Linguistic miracles of the Quran",
            "Practical reflections (tadabbur)",
        ],
        "outcomes": [
            "Grasp the deeper meanings of revelation",
            "Recognise the coherence of the Quran",
            "Reflect and act upon each verse",
        ],
        "order": 2,
    },
    {
        "id": "ramadan-2026",
        "title": "Ramadan Special 2026",
        "tag": "Seasonal",
        "level": "Open to all",
        "language": "English / Urdu",
        "duration": "1 Month",
        "start": "Mar 2026",
        "image": "clouds2",
        "desc": "Prepare your heart for the blessed month with focused lessons, duas and a daily worship checklist.",
        "longDesc": "A focused one-month program to prepare your heart and home for the blessed month of Ramadan, with daily lessons, essential duas and a practical worship checklist.",
        "instructor": "Guest Scholars",
        "days": "Daily (short sessions)",
        "time": "Early morning",
        "fee": "Free / Donation",
        "modules": [
            "Fiqh of fasting made simple",
            "Daily duas and adhkar",
            "Last ten nights game plan",
            "Worship & charity checklist",
        ],
        "outcomes": [
            "Enter Ramadan with clarity and intention",
            "Maximise reward in the blessed month",
            "Build habits that last beyond Ramadan",
        ],
        "order": 3,
    },
    {
        "id": "kids-course",
        "title": "Kids Course \u2014 Sem III",
        "tag": "Kids",
        "level": "Ages 5\u201312",
        "language": "English / Urdu",
        "duration": "3 Months",
        "start": "Apr 2025",
        "image": "leaves1",
        "desc": "Fun, interactive classes teaching little ones Quran basics, beautiful duas and the Seerah.",
        "longDesc": "A joyful, interactive course crafted for young hearts (ages 5\u201312). Through stories, activities and gentle guidance, children learn Quran basics, beautiful duas and the Seerah.",
        "instructor": "Kids Faculty",
        "days": "Sat \u2022 Sun",
        "time": "Weekend mornings",
        "fee": "From $25 / term",
        "modules": [
            "Quranic Arabic letters & short Surahs",
            "Everyday Masnoon duas",
            "Stories from the Seerah",
            "Good manners (Akhlaq) & kindness",
        ],
        "outcomes": [
            "Love for the Quran from an early age",
            "Confidence in recitation and duas",
            "Strong moral foundation",
        ],
        "order": 4,
    },
    {
        "id": "seerah-2026",
        "title": "Seerah Course 2026",
        "tag": "Seerah",
        "level": "Beginner",
        "language": "English",
        "duration": "1 Year",
        "start": "2026",
        "image": "greenForest",
        "desc": "Walk through the blessed biography of the Prophet \u00b7 and draw timeless lessons for today.",
        "longDesc": "A one-year journey through the blessed biography of the Prophet \u00b7 \u2014 from his noble lineage to the everlasting legacy of his message, with lessons for every stage of life.",
        "instructor": "Seerah Faculty",
        "days": "Fri",
        "time": "Evening slot",
        "fee": "From $35 / semester",
        "modules": [
            "The Makkan period & early da'wah",
            "The Hijrah and the Madinan society",
            "Battles, treaties and mercy",
            "The final sermon and legacy",
        ],
        "outcomes": [
            "Know the life of the Prophet \u00b7 in detail",
            "Draw timeless lessons for today",
            "Strengthen love for the Messenger \u00b7",
        ],
        "order": 5,
    },
    {
        "id": "al-lulu-wal-marjaan",
        "title": "Al Lulu Wal Marjaan",
        "tag": "Hadith",
        "level": "Advanced",
        "language": "English",
        "duration": "Semester I & II",
        "start": "2025",
        "image": "greenStream",
        "desc": "Agreed-upon ahadith of Bukhari & Muslim with practical guidance on crisis and life management.",
        "longDesc": "An advanced study of the agreed-upon ahadith of Bukhari and Muslim, paired with practical guidance on managing life's crises with patience and trust in Allah.",
        "instructor": "Hadith Faculty",
        "days": "Tue \u2022 Sat",
        "time": "Evening slot",
        "fee": "From $45 / semester",
        "modules": [
            "Authentication and the science of Hadith",
            "Selected agreed-upon narrations",
            "Crisis & life management from the Sunnah",
            "Practical application workshops",
        ],
        "outcomes": [
            "Engage with authentic Hadith confidently",
            "Navigate hardship with prophetic wisdom",
            "Apply the Sunnah in daily decisions",
        ],
        "order": 6,
    },
    {
        "id": "doors-of-jannah",
        "title": "Doors of Jannah",
        "tag": "Kids",
        "level": "Kids",
        "language": "English",
        "duration": "4 Weeks",
        "start": "July 11, 2026",
        "image": "https://nurulquran.com/wp-content/uploads/2026/06/000.png",
        "desc": "\"Race with one another toward forgiveness from your Lord and a Paradise as wide as the heavens and the earth.\"\n(Qur'an 57:21)",
        "longDesc": "Righteous Leaders Summer Camp 2026                  \"8 Doors of Jannah\"\n For Girls & Boys age 7 - 12years, Starting on Saturday July 11th to August 9th 2026 InshaAllah          \n [Note: Fill in 1 Form Per Child ]\n\nhttps://docs.google.com/forms/d/e/1FAIpQLSek23vHdV7QmuXCmU_7n81JqD9T8Wmq6noSWSwmJ4jQ-i4R0Q/viewform\n\n\n\"Every Good Deed Opens a Door.\"\n\nWhat if every good deed could bring you closer to one of the doors of Jannah?\n\nJoin us this summer as we explore the beautiful doors of Paradise mentioned in the Qur'an and Sunnah. Through inspiring stories, Quran,  hadith, interactive sessions, crafts, games, and real-life challenges, children will discover how to build habits that can lead them to Jannah. InshaAllah \n\nDaily Sunnah habits that help children become better Muslims at home and in school.\n\nEvery lesson is designed to strengthen faith, build beautiful character, and inspire children to strive for Jannatul Firdaus.\n\n\"Race with one another toward forgiveness from your Lord and a Paradise as wide as the heavens and the earth.\"\n(Qur'an 57:21)\n\nSaturdays & Sundays\n\nJuly 11th to August 9th\n\nUS/ESt: 8:15 AM - 9:15 AM\nUK: 1:15 PM \u2013 2:15 PM\nEurope: 2:15 PM \u2013 3:15 PM\nIndia: 5:45 PM \u2013 6:45 PM\nPakistan: 5:15 PM \u2013 6:15 PM\nSaudi Arabia: 3:15 PM \u2013 4:15 PM\nUAE: 4:15 PM \u2013 5:15 PM \nRecordings will be available incase if anyone needs inshaAllah",
        "instructor": "",
        "days": "Sat & Sun",
        "time": "",
        "fee": "",
        "modules": ["Quran", "Hadith", "Crafts", "Real Life Challenges"],
        "outcomes": ["Strong Faith", "Beautiful Character", "Grateful"],
        "order": 7,
    },
]
